USE gram_db;

CREATE TABLE USER
(
  USER_ID INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME    VARCHAR(32) NOT NULL
);

CREATE TABLE PHOTO_POST
(
  USER_ID       INT          NOT NULL,
  POST_ID       INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DESCRIPTION   VARCHAR(200) NOT NULL,
  CREATION_DATE DATETIME     NOT NULL,
  PHOTO_LINK    TEXT         NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
);